services:
  php:
    build: .
    container_name: php82
    volumes:
      - ./:/app
    working_dir: /app
    command: symfony serve --no-tls --port=8000 --allow-http --allow-all-ip
    ports:
      - "8000:8000"
